// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDrmsK_klw5A-rSgNHWNfUX_sICuMOCyQ',
    appId: '1:917311877967:web:78e076240a0a1816900b3a',
    messagingSenderId: '917311877967',
    projectId: 'task-manager-4d0b7',
    authDomain: 'task-manager-4d0b7.firebaseapp.com',
    storageBucket: 'task-manager-4d0b7.firebasestorage.app',
    measurementId: 'G-KMF28MGZJG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdUTgg0_9B57IxxK1xmohc3d6tzUFW9GM',
    appId: '1:917311877967:android:207b02fa930fb5eb900b3a',
    messagingSenderId: '917311877967',
    projectId: 'task-manager-4d0b7',
    storageBucket: 'task-manager-4d0b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDV0ByfaiqChSLtLnBl8TpqL4KSHKp-hQ',
    appId: '1:917311877967:ios:c8100da7510ffd22900b3a',
    messagingSenderId: '917311877967',
    projectId: 'task-manager-4d0b7',
    storageBucket: 'task-manager-4d0b7.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDV0ByfaiqChSLtLnBl8TpqL4KSHKp-hQ',
    appId: '1:917311877967:ios:c8100da7510ffd22900b3a',
    messagingSenderId: '917311877967',
    projectId: 'task-manager-4d0b7',
    storageBucket: 'task-manager-4d0b7.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDrmsK_klw5A-rSgNHWNfUX_sICuMOCyQ',
    appId: '1:917311877967:web:d1e56c360e31aad3900b3a',
    messagingSenderId: '917311877967',
    projectId: 'task-manager-4d0b7',
    authDomain: 'task-manager-4d0b7.firebaseapp.com',
    storageBucket: 'task-manager-4d0b7.firebasestorage.app',
    measurementId: 'G-KD1JVE2DB8',
  );
}
